# Generated by Django 3.0.6 on 2020-08-25 13:47

import allapps.models
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrier',
            fields=[
                ('id_Carrier', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Trasportatore')),
                ('address', models.CharField(max_length=50, verbose_name='indirizzo')),
            ],
            options={
                'verbose_name': 'Trasportatore',
                'verbose_name_plural': 'Trasportatori',
            },
        ),
        migrations.CreateModel(
            name='Cer',
            fields=[
                ('id_cer', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='codice CER')),
                ('description', models.CharField(max_length=100, verbose_name='descrizione CER')),
            ],
            options={
                'verbose_name': 'CER',
                'verbose_name_plural': 'Codici CER',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_Client', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='ID Cliente')),
                ('kind', models.CharField(choices=[('produttore', 'Produttore'), ('smaltitore', 'Smaltitore')], max_length=20, verbose_name='Tipologia')),
                ('lat', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='latitudine')),
                ('long', models.DecimalField(decimal_places=10, max_digits=15, verbose_name='longitudine')),
                ('timewindow_LB', models.TimeField(default=datetime.time(9, 0), verbose_name='Apertura')),
                ('timewindow_UB', models.TimeField(default=datetime.time(17, 0), verbose_name='Chiusura')),
                ('service_time', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tempo di servizio stimato [mm]')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clienti',
            },
        ),
        migrations.CreateModel(
            name='Input_App1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_LB', models.DateField()),
                ('horizon_UB', models.DateField()),
                ('dailyshifts', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('shift_1_hours', models.PositiveIntegerField(default=6)),
                ('shift_2_hours', models.PositiveIntegerField(default=3)),
                ('shift_3_hours', models.PositiveIntegerField(default=0)),
                ('operator_wage', models.PositiveIntegerField(default=15)),
                ('max_operators', models.PositiveIntegerField(default=8)),
                ('min_op_sort1', models.PositiveIntegerField(default=3)),
                ('min_op_sort2', models.PositiveIntegerField(default=6)),
                ('firstTO2nd_sort', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(100)])),
                ('setup_sort1', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(0)])),
                ('setup_sort2', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('overfill_treshold', models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('finalstock_treshold', models.PositiveIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(100)])),
                ('sort1_capacity', models.PositiveIntegerField(default=260)),
                ('sort2_capacity', models.PositiveIntegerField(default=220)),
                ('sort1_maxstock', models.PositiveIntegerField(default=60000)),
                ('sort2_maxstock', models.PositiveIntegerField(default=10000)),
            ],
            options={
                'verbose_name': 'Input App 1',
                'verbose_name_plural': 'Inputs App 1',
            },
        ),
        migrations.CreateModel(
            name='Input_App2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_cost', models.PositiveIntegerField(default=15)),
                ('distance_cost', models.PositiveIntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Input App 2',
                'verbose_name_plural': 'Inputs App 2',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id_exit', models.AutoField(primary_key=True, serialize=False, verbose_name='ID uscita')),
                ('date', models.DateField(verbose_name='data prevista')),
                ('case_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='numero casse')),
                ('Client_destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destination', to='allapps.Client', verbose_name='Destinazione trasporto')),
                ('Client_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origin', to='allapps.Client', verbose_name='Origine trasporto')),
            ],
            options={
                'verbose_name': 'Missione',
                'verbose_name_plural': 'Missioni',
            },
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('plate_number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Targa')),
                ('trasporter_type', models.CharField(choices=[('motrice', 'Motrice'), ('rimorchio', 'Rimorchio')], default=False, max_length=50, verbose_name='Tipologia mezzo')),
                ('add_trailer', models.BooleanField(default=False, verbose_name='può agganciare un rimorchio')),
                ('carrier_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allapps.Carrier', verbose_name='Trasportatore proprietario')),
            ],
            options={
                'verbose_name': 'mezzo di trasporto',
                'verbose_name_plural': 'mezzi di trasporto',
            },
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('load_capacity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(2)])),
                ('is_available', models.BooleanField(default=True, verbose_name='è disponibilie')),
                ('head', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='head', to='allapps.Transporter', verbose_name='Motrice')),
                ('trailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trailer', to='allapps.Transporter', verbose_name='Rimorchio')),
            ],
            options={
                'verbose_name': 'Automezzo',
                'verbose_name_plural': 'Automezzi',
            },
        ),
        migrations.CreateModel(
            name='Output_App2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_visit_order', models.CharField(max_length=100)),
                ('destination_visit_order', models.CharField(max_length=100)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allapps.Mission')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allapps.Input_App2')),
            ],
            options={
                'verbose_name': 'Output App 2',
                'verbose_name_plural': 'Outputs App 2',
            },
        ),
        migrations.CreateModel(
            name='Output_App1_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.CharField(choices=[('in esecuzione', 'in esecuzione'), ('completato', 'completato')], default='in esecuzione', max_length=40, verbose_name='stato')),
                ('input_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapps.Input_App1')),
            ],
            options={
                'verbose_name': 'Output App 1 - dettaglio',
                'verbose_name_plural': 'Outputs App 1 - dettagli',
            },
        ),
        migrations.CreateModel(
            name='Output_App1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_sorting', models.CharField(max_length=300, validators=[django.core.validators.int_list_validator], verbose_name='first sorting activation')),
                ('second_sorting', models.CharField(max_length=300, validators=[django.core.validators.int_list_validator], verbose_name='second sorting activation')),
                ('first_sort_operators', models.CharField(default=0, max_length=300, validators=[django.core.validators.int_list_validator])),
                ('second_sort_operators', models.CharField(default=0, max_length=300, validators=[django.core.validators.int_list_validator])),
                ('first_sort_amount', models.CharField(default=0, max_length=300, validators=[django.core.validators.int_list_validator])),
                ('second_sort_amount', models.CharField(default=0, max_length=300, validators=[django.core.validators.int_list_validator])),
                ('input_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapps.Input_App1')),
            ],
            options={
                'verbose_name': 'Output App 1',
                'verbose_name_plural': 'Outputs App 1',
            },
        ),
        migrations.CreateModel(
            name='Mix_unloading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data prevista')),
                ('working_shift', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)], verbose_name='turno previsto')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantità prevista')),
                ('id_Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allapps.Client', verbose_name='ID Cliente')),
            ],
            options={
                'verbose_name': 'Scarico 150106',
                'verbose_name_plural': 'Scarico misti',
            },
        ),
        migrations.CreateModel(
            name='Fir',
            fields=[
                ('fir_number', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Numero FIR')),
                ('net_weight', models.PositiveIntegerField(verbose_name='peso netto')),
                ('cer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allapps.Cer', verbose_name='CER')),
                ('exit_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allapps.Mission', verbose_name='ID_uscita')),
                ('id_carrier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='allapps.Carrier', verbose_name='Trasportatore')),
                ('id_disposer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disposer', to='allapps.Client', verbose_name='Smaltitore')),
                ('id_producer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producer', to='allapps.Client', verbose_name='Produttore')),
                ('plate_number_trailer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trailer_plate', to='allapps.Transporter', validators=[allapps.models.Fir.val_trailer], verbose_name='Targa rimorchio')),
                ('plate_number_truck', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='truck_plate', to='allapps.Transporter', validators=[allapps.models.Fir.val_truck], verbose_name='Targa motrice')),
            ],
            options={
                'verbose_name': 'Fir',
                'verbose_name_plural': 'Formulari',
            },
        ),
    ]
